### ISSUE TITLE
Issue: Llama_avg Merge Fails with TypeError

### ISSUE THREAD

**Issue by wakasturner** [llm-merging/LLM-Merging#10]
**Description:**
The starter merging `flan_t5_avg` works successfully using the following command:
`python llm_merging/main.py -m flan_t5_avg`

However, the `llama_avg` merge fails with the following error:
`python llm_merging/main.py -m llama_avg`

**Error:**
`TypeError: LlamaTokenizerFast.__init__() got multiple values for argument 'vocab_file'`

**Expected Behavior:**
The llama_avg merge should complete successfully without throwing a TypeError.

**Actual Behavior:**
The llama_avg merge fails with a TypeError related to LlamaTokenizerFast.

**Comment by dptam** [comment]
Do you have the stack trace? And what transformers version are you using (`pip freeze | grep transformers`)?

**Comment by wakasturner** [comment]
Following is the traceback

`
Traceback (most recent call last):
  File "/home/USERNAME/wakas/LLM-Merging/llm_merging/main.py", line 27, in <module>
    merge_method.merge()
  File "/home/USERNAME/wakas/LLM-Merging/llm_merging/merging/LlamaAvg.py", line 81, in merge
    self._load_tokenizer()
  File "/home/USERNAME/wakas/LLM-Merging/llm_merging/merging/Merges.py", line 75, in _load_tokenizer
    self.input_tokenizer = AutoTokenizer.from_pretrained(
  File "/home/USERNAME/miniconda3/envs/llm-merging/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 837, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/USERNAME/miniconda3/envs/llm-merging/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2086, in from_pretrained
    return cls._from_pretrained(
  File "/home/USERNAME/miniconda3/envs/llm-merging/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2325, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
TypeError: LlamaTokenizerFast.__init__() got multiple values for argument 'vocab_file'
`
My transformers version is transformers==4.39.3
Also tried to downgrade to transformers==4.36.0 but still same error

**Comment by dptam** [comment]
Thanks for posting the traceback. It should be fixed now with the new commit.

**Comment by wakasturner** [comment]
I can confirm that the latest commit fixes the error, and both `flan_t5_avg` and `llama_avg `are now running successfully.
